/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;700&display=swap'
          rel='stylesheet'
        />
      </Head>
      <Navbar />
    </>
  );
}
